# Detects the current Wi-Fi/Ethernet LAN IPv4 and writes it into
# apps\mobile\.env as EXPO_PUBLIC_API_URL. Run this whenever you switch
# networks (or wire it up to run automatically — see package.json "predev").
#
#   powershell -ExecutionPolicy Bypass -File scripts\sync-lan-ip.ps1
#
# This does NOT fix Windows blocking inbound connections on "Public"
# networks — that's solved once, permanently, by adding firewall rules for
# all profiles (see docs/runbooks/mobile-dev.md).

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$envFile = Join-Path $root "apps\mobile\.env"

# Prefer a real Wi-Fi/Ethernet adapter over VPN/virtual/WSL adapters.
$candidates = Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object {
        $_.IPAddress -notlike '127.*' -and
        $_.IPAddress -notlike '169.254.*' -and
        $_.InterfaceAlias -notmatch 'vEthernet|Loopback|WSL|VPN|Tailscale'
    }

$preferred = $candidates | Where-Object { $_.InterfaceAlias -match '^Wi-Fi' } | Select-Object -First 1
if (-not $preferred) { $preferred = $candidates | Select-Object -First 1 }

if (-not $preferred) {
    Write-Error "No usable LAN IPv4 address found. Are you connected to a network?"
    exit 1
}

$ip = $preferred.IPAddress
$content = @"
# API base URL as reachable FROM THE PHONE (your PC's LAN IP, not localhost).
# Auto-generated by scripts\sync-lan-ip.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm') - re-run after switching networks.
EXPO_PUBLIC_API_URL=http://${ip}:3000
"@

Set-Content -Path $envFile -Value $content -Encoding utf8 -NoNewline
Write-Host "apps/mobile/.env -> EXPO_PUBLIC_API_URL=http://${ip}:3000  (interface: $($preferred.InterfaceAlias))"
Write-Host "Restart Metro (npx expo start --dev-client --clear) for the change to take effect."
